<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="107809" started-at="2023-08-10T14:14:29Z" finished-at="2023-08-10T14:16:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="107809" started-at="2023-08-10T14:14:29Z" finished-at="2023-08-10T14:16:17Z">
      <class name="com.amazon.testcases.TestCases">
        <test-method status="PASS" signature="report()[pri:0, instance:com.amazon.testcases.TestCases@490ab905]" name="report" is-config="true" duration-ms="270" started-at="2023-08-10T14:14:29Z" finished-at="2023-08-10T14:14:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method status="PASS" signature="setuplog()[pri:0, instance:com.amazon.testcases.TestCases@490ab905]" name="setuplog" is-config="true" duration-ms="34" started-at="2023-08-10T14:14:29Z" finished-at="2023-08-10T14:14:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setuplog -->
        <test-method status="PASS" signature="method(java.lang.reflect.Method)[pri:0, instance:com.amazon.testcases.TestCases@490ab905]" name="method" is-config="true" duration-ms="6" started-at="2023-08-10T14:14:29Z" finished-at="2023-08-10T14:14:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.amazon.testcases.TestCases.Test() throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="Test()[pri:0, instance:com.amazon.testcases.TestCases@490ab905]" name="Test" duration-ms="106023" started-at="2023-08-10T14:14:29Z" finished-at="2023-08-10T14:16:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Practical Process Automation: Orchestration and Integration in Microservices and Cloud Native Architectures] but found [Practical Process]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Practical Process Automation: Orchestration and Integration in Microservices and Cloud Native Architectures] but found [Practical Process]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.amazon.testcases.TestCases.Test(TestCases.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.amazon.testcases.TestCases@490ab905]" name="tearDown" is-config="true" duration-ms="1451" started-at="2023-08-10T14:16:15Z" finished-at="2023-08-10T14:16:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.amazon.testcases.TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
